// This file was autogenerated by /Users/adam/dev/libs/javascript/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../grow/fx/shake.js', ['grow.fx.Shake'], ['goog.fx.AnimationSerialQueue', 'goog.fx.dom.Slide', 'goog.fx.easing']);
