// This file was autogenerated by /Users/adam/dev/libs/javascript/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../grow/fx/dom/shake.js', ['grow.fx.dom.Shake'], ['goog.fx.dom.Slide']);
